package com.blazepush.simulator.data.replay

import org.junit.Assert.assertEquals
import org.junit.Test

class RaceChronoReplayParserTest {

    @Test
    fun `parseCsv extracts replay samples with main gps fields`() {
        val csv = """
            This file is created using RaceChrono Pro v10.0.4 ( http://racechrono.com/ ).
            Format,3
            Session title,"天府赛道"
            Session type,Lap timing
            Track name,"天府赛道"
            Driver name,
            Created,14/03/2026,08:41
            Note,

            timestamp,fragment_id,lap_number,elapsed_time,distance_traveled,altitude,altitude_precision,bearing,coordinate_precision,device_update_rate,fix_type,latitude,longitude,satellites,speed
            unix time,,,s,m,m,DOP,deg,DOP,Hz,,deg,deg,sats,m/s
            ,,,,,200: gps,200: gps,200: gps,200: gps,200: gps,200: gps,200: gps,200: gps,200: gps,200: gps
            1773477689.648,0,,0.008,0.0,444.0,0.0,212.91,0.9,25.0,1.0,30.4945735,104.4332358,12.0,0.0104
            1773477689.740,0,,0.100,0.019,444.2,0.0,189.30,0.8,25.0,1.0,30.4945740,104.4332365,11.0,0.0640
        """.trimIndent()

        val replay = RaceChronoReplayParser().parseCsv(csv)

        assertEquals("天府赛道", replay.sessionTitle)
        assertEquals(2, replay.samples.size)
        assertEquals(1773477689648L, replay.samples[0].timestampMillis)
        assertEquals(30.4945735, replay.samples[0].latitude, 0.0000001)
        assertEquals(104.4332358, replay.samples[0].longitude, 0.0000001)
        assertEquals(0.0104 * 3.6, replay.samples[0].speedKmh, 0.0001)
        assertEquals(12, replay.samples[0].satellites)
        assertEquals(1, replay.samples[0].fixType)
        assertEquals(0.9, replay.samples[0].hdop, 0.0001)
        assertEquals(444.0, replay.samples[0].altitudeMeters, 0.0001)
    }

    @Test
    fun `parseVbo extracts start and split gates as line segments`() {
        val vbo = """
            File created on 14/03/2026 at 08:41:28

            [header]
            satellites
            time
            latitude
            longitude
            velocity kmh
            heading
            height

            [comments]
            Generated by RaceChrono Pro v10.0.4
            http://racechrono.com/

            [session data]
            name 天府赛道

            [laptiming]
            Start   -6265.990660 +1829.770740 -6265.992299 +1829.797683 ¬ 起点
            Split   -6266.233360 +1829.745710 -6266.233906 +1829.718734 ¬ s2
            Split   -6265.953260 +1829.389270 -6265.922122 +1829.386450 ¬ s1

            [data]
            012 084129.74 +1829.674400 -06265.994150 000.230 212.91 +00444.00
        """.trimIndent()

        val referenceSample = ReplaySample(
            timestampMillis = 1773477689648L,
            latitude = 30.4945735,
            longitude = 104.4332358,
            speedKmh = 0.0104 * 3.6,
            bearingDegrees = 212.91,
            satellites = 12,
            fixType = 1,
            hdop = 0.9,
            altitudeMeters = 444.0,
            altitudePrecisionMeters = 0.0
        )

        val gates = RaceChronoReplayParser().parseVboGates(vbo, referenceSample)

        assertEquals(3, gates.size)
        assertEquals(RaceChronoGateType.StartFinish, gates[0].type)
        assertEquals("起点", gates[0].name)
        assertEquals(30.496179, gates[0].line.start.latitude, 0.000001)
        assertEquals(104.433294, gates[0].line.start.longitude, 0.000001)
        assertEquals(RaceChronoGateType.Split, gates[1].type)
        assertEquals("s2", gates[1].name)
        assertEquals("s1", gates[2].name)
    }

    @Test
    fun `parseVbo aligns gates using nearest data row to reference sample time`() {
        val vbo = """
            [laptiming]
            Start   -6265.990660 +1829.770740 -6265.992299 +1829.797683 ¬ 起点

            [data]
            012 084129.74 +1829.674400 -06265.994150 000.230 212.91 +00444.00
            012 085236.53 +1830.000000 -06266.100000 100.000 179.80 +00424.20
        """.trimIndent()

        val referenceSample = ReplaySample(
            timestampMillis = 1773478356533L,
            latitude = 30.496179,
            longitude = 104.4331783,
            speedKmh = 96.68232,
            bearingDegrees = 179.8,
            satellites = 12,
            fixType = 1,
            hdop = 0.9,
            altitudeMeters = 424.2,
            altitudePrecisionMeters = 0.0
        )

        val gates = RaceChronoReplayParser().parseVboGates(vbo, referenceSample)

        assertEquals(1, gates.size)
        assertEquals(30.492358, gates[0].line.start.latitude, 0.000001)
        assertEquals(104.43500063333335, gates[0].line.start.longitude, 0.000001)
    }
}
