package com.blazepush.feature.test.export

import com.blazepush.core.data.repository.TelemetryRepository
import com.blazepush.core.domain.model.LapConfidencePolicy
import com.blazepush.core.domain.model.TelemetrySample
import com.blazepush.feature.test.model.track.GeoPoint
import com.blazepush.feature.test.model.track.TimingGate
import com.blazepush.feature.test.model.track.Track
import java.io.Writer
import java.time.Instant
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter
import java.util.Locale

/** Streaming whole-session RaceLogic VBO formatter. */
object RaceLogicVboSessionExporter {
    private const val MIN_RELIABLE_EPOCH_MS = 946_684_800_000L
    private const val MAX_RELIABLE_EPOCH_MS = 4_102_444_800_000L
    private val createdAtFormatter = DateTimeFormatter.ofPattern("dd/MM/uuuu 'at' HH:mm:ss", Locale.US)
        .withZone(ZoneOffset.UTC)
    private val fileNameFormatter = DateTimeFormatter.ofPattern("uuuu-MM-dd_HH-mm-ss", Locale.US)
        .withZone(ZoneOffset.UTC)
    private val timeFormatter = DateTimeFormatter.ofPattern("HHmmss.SS", Locale.US)
        .withZone(ZoneOffset.UTC)

    data class Document(
        val fileName: String,
        val exportedSampleCount: Int,
        val omittedSampleCount: Int,
        val headingIncluded: Boolean,
        val completeLapCount: Int,
        val laptimingIncluded: Boolean,
    )

    enum class Rejection { EMPTY_SAMPLES, NO_VALID_POSITION_SAMPLES, NO_VALID_REQUIRED_FIELDS }

    sealed class Result {
        data class Ready(val document: Document) : Result()
        data class Rejected(val reason: Rejection) : Result()
    }

    fun write(
        snapshot: TelemetryRepository.LapSessionExportSnapshot,
        track: Track?,
        writer: Writer,
    ): Result {
        if (snapshot.samples.isEmpty()) return Result.Rejected(Rejection.EMPTY_SAMPLES)
        val positioned = snapshot.samples.filter(::hasValidPosition)
        if (positioned.isEmpty()) return Result.Rejected(Rejection.NO_VALID_POSITION_SAMPLES)
        val exportable = positioned.mapNotNull { sample ->
            val absoluteTs = safeAbsoluteTs(snapshot.session.startTs, sample) ?: return@mapNotNull null
            if (!hasValidRequiredFields(sample, absoluteTs)) return@mapNotNull null
            ExportRow(sample, absoluteTs)
        }
        if (exportable.isEmpty()) return Result.Rejected(Rejection.NO_VALID_REQUIRED_FIELDS)

        val headingIncluded = exportable.all { row ->
            row.sample.bearingDeg?.let { it.isFinite() && it >= 0.0 && it < 360.0 } == true
        }
        val completeLaps = snapshot.crossings
            .asSequence()
            .filter { it.accepted && it.gateType.equals("StartFinish", ignoreCase = true) }
            .mapNotNull { crossing -> crossing.crossingWallClockTimestampMs?.let { it to crossing } }
            .sortedBy { it.first }
            .map { it.second }
            .zipWithNext()
            .filter { (start, finish) ->
                val startTs = start.crossingWallClockTimestampMs
                val finishTs = finish.crossingWallClockTimestampMs
                startTs != null && finishTs != null && finishTs > startTs
            }
            .toList()
        val fileTimeMs = snapshot.session.startTs.takeIf(::isReliableTimestamp) ?: exportable.first().absoluteTsMs
        val displayTrack = snapshot.session.trackNameSnapshot ?: snapshot.session.trackId ?: "Track"
        val fileName = buildFileName(displayTrack, fileTimeMs)

        writer.append("File created on ")
            .append(createdAtFormatter.format(Instant.ofEpochMilli(fileTimeMs)))
            .append(" UTC\n\n")
        writer.append("[header]\n")
            .append("time\nlatitude\nlongitude\nvelocity kmh\n")
        if (headingIncluded) writer.append("heading\n")
        writer.append("\n[comments]\n")
            .append("Generated by gps-app from complete persisted lap-session evidence\n")
            .append("Session ID: ").append(singleLine(snapshot.session.sessionId)).append('\n')
            .append("Track: ").append(singleLine(displayTrack)).append('\n')
            .append("Scope: complete session including samples outside complete lap windows\n")
            .append("Complete laps: ").append(completeLaps.size.toString()).append('\n')
            .append("Timestamp basis: UTC; precision: 0.01 seconds\n")
        if (track == null) writer.append("Laptiming omitted: track geometry unavailable\n")
        if (completeLaps.isEmpty()) writer.append("Lap summary: no complete start-finish pair\n")
        completeLaps.forEachIndexed { index, (start, finish) ->
            val startTs = requireNotNull(start.crossingWallClockTimestampMs)
            val finishTs = requireNotNull(finish.crossingWallClockTimestampMs)
            val quality = LapConfidencePolicy.evaluate(snapshot.evidenceByLap[index + 1])
            writer.append("Lap ").append((index + 1).toString())
                .append(": durationMs=").append((finishTs - startTs).toString())
                .append("; confidence=").append(quality.confidence.name)
                .append("; provenance=").append(quality.provenance.name)
                .append('\n')
        }
        val omittedCount = snapshot.samples.size - exportable.size
        if (omittedCount > 0) writer.append("Omitted invalid samples: ").append(omittedCount.toString()).append('\n')
        if (!headingIncluded) writer.append("Heading omitted: not present and valid on every exported sample\n")

        writer.append("\n[session data]\nname ")
            .append(singleLine(displayTrack))
            .append(" - Session ")
            .append(singleLine(snapshot.session.sessionId))
            .append('\n')
        if (track != null) {
            writer.append("\n[laptiming]\n")
            writeGate(writer, "Start", track.startFinishGate)
            track.orderedSectorGates.forEach { writeGate(writer, "Split", it) }
        }
        writer.append("\n[column names]\n")
            .append(if (headingIncluded) "time lat long velocity heading\n" else "time lat long velocity\n")
            .append("\n[data]\n")
        exportable.forEach { row ->
            writeRow(writer, row, headingIncluded)
            writer.append('\n')
        }
        writer.flush()

        return Result.Ready(
            Document(
                fileName = fileName,
                exportedSampleCount = exportable.size,
                omittedSampleCount = omittedCount,
                headingIncluded = headingIncluded,
                completeLapCount = completeLaps.size,
                laptimingIncluded = track != null,
            ),
        )
    }

    private data class ExportRow(val sample: TelemetrySample, val absoluteTsMs: Long)

    private fun writeGate(writer: Writer, label: String, gate: TimingGate) {
        writer.append(label.padEnd(8))
            .append(formatLongitude(gate.line.start)).append(' ')
            .append(formatLatitude(gate.line.start)).append(' ')
            .append(formatLongitude(gate.line.end)).append(' ')
            .append(formatLatitude(gate.line.end)).append(" ¬ ")
            .append(singleLine(gate.name)).append('\n')
    }

    private fun writeRow(writer: Writer, row: ExportRow, headingIncluded: Boolean) {
        val roundedToCentisecond = Math.floorDiv(row.absoluteTsMs + 5L, 10L) * 10L
        writer.append(timeFormatter.format(Instant.ofEpochMilli(roundedToCentisecond))).append(' ')
            .append(String.format(Locale.US, "%+014.8f", row.sample.lat * 60.0)).append(' ')
            .append(String.format(Locale.US, "%+014.8f", row.sample.lon * -60.0)).append(' ')
            .append(String.format(Locale.US, "%.3f", row.sample.speedKmh))
        if (headingIncluded) {
            writer.append(' ').append(String.format(Locale.US, "%.2f", requireNotNull(row.sample.bearingDeg)))
        }
    }

    fun buildFileName(trackName: String, timestampMs: Long): String =
        "${safeComponent(trackName, 48)}_${fileNameFormatter.format(Instant.ofEpochMilli(timestampMs))}_session.vbo"

    private fun formatLongitude(point: GeoPoint): String =
        String.format(Locale.US, "%+014.8f", point.longitude * -60.0)

    private fun formatLatitude(point: GeoPoint): String =
        String.format(Locale.US, "%+014.8f", point.latitude * 60.0)

    private fun hasValidPosition(sample: TelemetrySample): Boolean =
        sample.lat.isFinite() && sample.lat in -90.0..90.0 &&
            sample.lon.isFinite() && sample.lon in -180.0..180.0

    private fun hasValidRequiredFields(sample: TelemetrySample, absoluteTsMs: Long): Boolean =
        isReliableTimestamp(absoluteTsMs) && sample.speedKmh.isFinite() && sample.speedKmh >= 0.0

    private fun safeAbsoluteTs(sessionStartTs: Long, sample: TelemetrySample): Long? =
        runCatching { Math.addExact(sessionStartTs, sample.tsDeltaMs) }.getOrNull()

    private fun isReliableTimestamp(timestampMs: Long): Boolean =
        timestampMs in MIN_RELIABLE_EPOCH_MS until MAX_RELIABLE_EPOCH_MS

    private fun safeComponent(raw: String, maxLength: Int): String = raw.trim()
        .replace(Regex("[\\p{Cntrl}\\\\/:*?\"<>|]+"), "-")
        .replace(Regex("\\s+"), "-")
        .replace(Regex("-+"), "-")
        .trim('-', '.', ' ')
        .ifBlank { "track" }
        .take(maxLength)

    private fun singleLine(value: String): String = value.replace(Regex("[\\r\\n]+"), " ").trim()
}
