package com.blazepush.feature.test.export

import com.blazepush.core.domain.model.LapConfidence
import com.blazepush.core.domain.model.LapConfidencePolicy
import com.blazepush.core.domain.model.LapEvidence
import com.blazepush.core.domain.model.LapReviewProvenance
import com.blazepush.core.domain.model.LapTelemetry
import com.blazepush.core.domain.model.LapTelemetrySample
import java.time.Instant
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter
import java.util.Locale
import java.util.zip.CRC32

/**
 * Pure single-lap RaceLogic VBO formatter. Android UI owns SAF and result feedback.
 *
 * Format source: https://en.racelogic.support/knowledge-bases/general-kb/vbo-files/
 * The official format defines space-delimited data whose shape is declared by [column names], UTC
 * HHMMSS.SS time, signed total-arc-minute coordinates (North/West positive), km/h, and heading from
 * true North. The minimal-column choice is an explicit inference from that declared-column contract
 * plus the repository's real tianfu_track.vbo fixture: unknown channels are omitted, never fabricated.
 */
object RaceLogicVboLapExporter {
    // Wall-clock telemetry outside this conservative product range is not presented as a real date.
    private const val MIN_RELIABLE_EPOCH_MS = 946_684_800_000L // 2000-01-01T00:00:00Z
    private const val MAX_RELIABLE_EPOCH_MS = 4_102_444_800_000L // 2100-01-01T00:00:00Z
    private val createdAtFormatter = DateTimeFormatter.ofPattern("dd/MM/uuuu 'at' HH:mm:ss", Locale.US)
        .withZone(ZoneOffset.UTC)
    private val timeFormatter = DateTimeFormatter.ofPattern("HHmmss.SS", Locale.US)
        .withZone(ZoneOffset.UTC)

    data class Metadata(
        val confidence: LapConfidence,
        val provenance: LapReviewProvenance,
    )

    data class Document(
        val fileName: String,
        val text: String,
        val exportedSampleCount: Int,
        val omittedSampleCount: Int,
        val headingIncluded: Boolean,
        val boundaryComplete: Boolean,
        val fileTimeSource: FileTimeSource,
    )

    enum class FileTimeSource { LAP_START, FIRST_EXPORTED_SAMPLE }

    enum class Rejection { EMPTY_SAMPLES, NO_VALID_POSITION_SAMPLES, NO_VALID_REQUIRED_FIELDS }

    sealed class Result {
        data class Ready(val document: Document) : Result()
        data class Rejected(val reason: Rejection) : Result()
    }

    fun export(telemetry: LapTelemetry, metadata: Metadata): Result {
        if (telemetry.samples.isEmpty()) return Result.Rejected(Rejection.EMPTY_SAMPLES)

        val positioned = telemetry.samples.filter(::hasValidPosition)
        if (positioned.isEmpty()) return Result.Rejected(Rejection.NO_VALID_POSITION_SAMPLES)
        val exportable = positioned.filter(::hasValidRequiredFields)
        if (exportable.isEmpty()) return Result.Rejected(Rejection.NO_VALID_REQUIRED_FIELDS)

        val headingIncluded = exportable.all { sample ->
            sample.bearingDeg?.let { it.isFinite() && it >= 0.0 && it < 360.0 } == true
        }
        val boundaryComplete = isReliableTimestamp(telemetry.lapStartWallClock) &&
            isReliableTimestamp(telemetry.lapEndWallClock) &&
            telemetry.lapEndWallClock > telemetry.lapStartWallClock &&
            telemetry.lapDurationMs == telemetry.lapEndWallClock - telemetry.lapStartWallClock
        val fileTimeSource = if (isReliableTimestamp(telemetry.lapStartWallClock)) {
            FileTimeSource.LAP_START
        } else {
            FileTimeSource.FIRST_EXPORTED_SAMPLE
        }
        val fileTimestampMs = when (fileTimeSource) {
            FileTimeSource.LAP_START -> telemetry.lapStartWallClock
            FileTimeSource.FIRST_EXPORTED_SAMPLE -> exportable.first().absoluteTsMs
        }
        val fileName = buildFileName(
            trackName = telemetry.trackNameSnapshot ?: telemetry.trackId ?: "track",
            sessionId = telemetry.sessionId,
            lapNumber = telemetry.lapIndex + 1,
        )
        val text = buildString {
            append("File created on ")
            append(createdAtFormatter.format(Instant.ofEpochMilli(fileTimestampMs)))
            append(" UTC\n\n")
            append("[header]\n")
            append("time\nlatitude\nlongitude\nvelocity kmh\n")
            if (headingIncluded) append("heading\n")
            append("\n[comments]\n")
            append("Generated by gps-app from getLapTelemetry single-lap evidence\n")
            append("Session ID: ${singleLine(telemetry.sessionId)}\n")
            append("Track: ${singleLine(telemetry.trackNameSnapshot ?: telemetry.trackId ?: "unknown")}\n")
            append("Lap number: ${telemetry.lapIndex + 1}\n")
            append("Lap confidence: ${metadata.confidence.name}\n")
            append("Review provenance: ${metadata.provenance.name}\n")
            append("Lap boundary: ${if (boundaryComplete) "complete" else "incomplete"}\n")
            append("Timestamp basis: UTC; precision: 0.01 seconds\n")
            append("File time source: ${fileTimeSource.name.lowercase(Locale.US).replace('_', ' ')}\n")
            if (!headingIncluded) append("Heading omitted: not present and valid on every exported sample\n")
            val omittedCount = telemetry.samples.size - exportable.size
            if (omittedCount > 0) append("Omitted invalid samples: $omittedCount\n")
            append("\n[session data]\n")
            append("name ${singleLine(telemetry.trackNameSnapshot ?: telemetry.trackId ?: "Track")} - ")
            append("Session ${singleLine(telemetry.sessionId)} - Lap ${telemetry.lapIndex + 1}\n")
            append("\n[column names]\n")
            append(if (headingIncluded) "time lat long velocity heading\n" else "time lat long velocity\n")
            append("\n[data]\n")
            exportable.forEach { sample ->
                append(formatRow(sample, headingIncluded))
                append('\n')
            }
        }
        return Result.Ready(
            Document(
                fileName = fileName,
                text = text,
                exportedSampleCount = exportable.size,
                omittedSampleCount = telemetry.samples.size - exportable.size,
                headingIncluded = headingIncluded,
                boundaryComplete = boundaryComplete,
                fileTimeSource = fileTimeSource,
            ),
        )
    }

    fun buildFileName(trackName: String, sessionId: String, lapNumber: Int): String {
        val track = safeComponent(trackName.ifBlank { "track" }, 48)
        val session = safeComponent(sessionId.ifBlank { "session" }, 48)
        return "${track}_${session}_lap-${lapNumber.coerceAtLeast(1).toString().padStart(2, '0')}.vbo"
    }

    private fun hasValidPosition(sample: LapTelemetrySample): Boolean =
        sample.lat.isFinite() && sample.lat in -90.0..90.0 &&
            sample.lon.isFinite() && sample.lon in -180.0..180.0

    private fun hasValidRequiredFields(sample: LapTelemetrySample): Boolean =
        isReliableTimestamp(sample.absoluteTsMs) && sample.speedKmh.isFinite() && sample.speedKmh >= 0.0

    private fun isReliableTimestamp(timestampMs: Long): Boolean =
        timestampMs in MIN_RELIABLE_EPOCH_MS until MAX_RELIABLE_EPOCH_MS

    private fun formatRow(sample: LapTelemetrySample, headingIncluded: Boolean): String {
        // RaceLogic VBO positions are signed total arc-minutes: North/West positive.
        val latitudeMinutes = sample.lat * 60.0
        val longitudeMinutes = sample.lon * -60.0
        val roundedToCentisecond = Math.floorDiv(sample.absoluteTsMs + 5L, 10L) * 10L
        return buildString {
            append(timeFormatter.format(Instant.ofEpochMilli(roundedToCentisecond)))
            append(' ')
            append(String.format(Locale.US, "%+014.8f", latitudeMinutes))
            append(' ')
            append(String.format(Locale.US, "%+014.8f", longitudeMinutes))
            append(' ')
            append(String.format(Locale.US, "%.3f", sample.speedKmh))
            if (headingIncluded) {
                append(' ')
                append(String.format(Locale.US, "%.2f", requireNotNull(sample.bearingDeg)))
            }
        }
    }

    private fun safeComponent(raw: String, maxLength: Int): String {
        val normalized = raw.trim()
            .replace(Regex("[\\p{Cntrl}\\\\/:*?\"<>|]+"), "-")
            .replace(Regex("\\s+"), "-")
            .replace(Regex("-+"), "-")
            .trim('-', '.', ' ')
            .ifBlank { "unknown" }
        if (normalized.length <= maxLength) return normalized
        val crc = CRC32().apply { update(normalized.toByteArray(Charsets.UTF_8)) }.value
        val suffix = "-%08x".format(Locale.US, crc)
        return normalized.take(maxLength - suffix.length).trimEnd('-', '.', ' ') + suffix
    }

    private fun singleLine(value: String): String = value.replace(Regex("[\\r\\n]+"), " ").trim()
}

/** Pure export readiness: a loaded-null evidence value is distinct from evidence still loading. */
sealed class LapVboExportPreparation {
    object Loading : LapVboExportPreparation()
    object NoTelemetry : LapVboExportPreparation()
    data class Ready(
        val telemetry: LapTelemetry,
        val metadata: RaceLogicVboLapExporter.Metadata,
    ) : LapVboExportPreparation()

    companion object {
        fun resolve(
            telemetry: LapTelemetry?,
            evidence: LapEvidence?,
            evidenceLoaded: Boolean,
        ): LapVboExportPreparation {
            if (!evidenceLoaded) return Loading
            if (telemetry == null) return NoTelemetry
            val quality = LapConfidencePolicy.evaluate(evidence)
            return Ready(
                telemetry,
                RaceLogicVboLapExporter.Metadata(quality.confidence, quality.provenance),
            )
        }
    }
}

/** Small strict reader for formatter round-trip tests and future repository-local replay checks. */
object RaceLogicVboTelemetryParser {
    data class Row(
        val utcMillisOfDay: Long,
        val latitudeDegrees: Double,
        val longitudeDegrees: Double,
        val speedKmh: Double,
        val headingDegrees: Double?,
    )

    fun parse(text: String): List<Row> {
        val lines = text.lineSequence().map(String::trim).toList()
        val columnMarker = lines.indexOf("[column names]")
        val dataMarker = lines.indexOf("[data]")
        require(columnMarker >= 0 && dataMarker > columnMarker + 1) { "VBO columns or data section missing" }
        val columns = lines.drop(columnMarker + 1).first { it.isNotEmpty() }.split(Regex("\\s+"))
        val required = listOf("time", "lat", "long", "velocity")
        require(required.all(columns::contains)) { "Required minimal VBO columns missing" }
        return lines.drop(dataMarker + 1).filter(String::isNotEmpty).map { line ->
            val parts = line.split(Regex("\\s+"))
            require(parts.size == columns.size) { "VBO row does not match columns" }
            val values = columns.zip(parts).toMap()
            Row(
                utcMillisOfDay = parseTime(requireNotNull(values["time"])),
                latitudeDegrees = requireNotNull(values["lat"]).toDouble() / 60.0,
                longitudeDegrees = requireNotNull(values["long"]).toDouble() / -60.0,
                speedKmh = requireNotNull(values["velocity"]).toDouble(),
                headingDegrees = values["heading"]?.toDouble(),
            )
        }
    }

    private fun parseTime(value: String): Long {
        require(Regex("\\d{6}\\.\\d{2}").matches(value)) { "Invalid VBO UTC time" }
        val hours = value.substring(0, 2).toLong()
        val minutes = value.substring(2, 4).toLong()
        val seconds = value.substring(4, 6).toLong()
        val centiseconds = value.substring(7, 9).toLong()
        return (((hours * 60L + minutes) * 60L + seconds) * 1000L) + centiseconds * 10L
    }
}
